// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@firstweb.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/getmenu": {
            "get": {
                "description": "根据用户角色获取相应的权限菜单，支持树形结构",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "获取用户权限菜单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "角色ID，为空或0时返回全部菜单",
                        "name": "role",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "用户信息错误",
                        "schema": {
                            "$ref": "#/definitions/sysbase.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "菜单树形结构",
                        "schema": {
                            "$ref": "#/definitions/sysbase.MenuResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "用户登录接口，使用SM2解密密码并验证用户身份",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "loginRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/sysbase.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "101": {
                        "description": "解密失败或其他错误",
                        "schema": {
                            "$ref": "#/definitions/sysbase.ErrorResponse"
                        }
                    },
                    "102": {
                        "description": "无效的请求参数",
                        "schema": {
                            "$ref": "#/definitions/sysbase.ErrorResponse"
                        }
                    },
                    "103": {
                        "description": "用户名或密码错误",
                        "schema": {
                            "$ref": "#/definitions/sysbase.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "登录成功，返回token",
                        "schema": {
                            "$ref": "#/definitions/sysbase.LoginResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "用户登出接口，清除用户token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "请先登录",
                        "schema": {
                            "$ref": "#/definitions/sysbase.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "退出成功",
                        "schema": {
                            "$ref": "#/definitions/sysbase.LogoutResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/userinfo": {
            "get": {
                "description": "根据token获取当前登录用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户token",
                        "name": "Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "解析用户信息失败",
                        "schema": {
                            "$ref": "#/definitions/sysbase.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "用户信息",
                        "schema": {
                            "$ref": "#/definitions/sysbase.UserInfoResponse"
                        }
                    },
                    "401": {
                        "description": "未授权，请先登录",
                        "schema": {
                            "$ref": "#/definitions/sysbase.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/db/delete": {
            "post": {
                "description": "根据ID删除指定表中的数据记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库通用操作"
                ],
                "summary": "删除数据",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"users\"",
                        "description": "表名",
                        "name": "table",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"1\"",
                        "description": "要删除的记录ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "104": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.DeleteResponse"
                        }
                    }
                }
            }
        },
        "/api/db/detail": {
            "get": {
                "description": "根据ID获取指定表中单条记录的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库通用操作"
                ],
                "summary": "获取详情数据",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"users\"",
                        "description": "表名",
                        "name": "table",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"1\"",
                        "description": "记录ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "104": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "查询成功，返回记录详情",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.DetailResponse"
                        }
                    }
                }
            }
        },
        "/api/db/list": {
            "post": {
                "description": "支持复杂条件查询的通用列表接口，不分页返回所有符合条件的数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库通用操作"
                ],
                "summary": "列表查询数据",
                "responses": {
                    "101": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "102": {
                        "description": "表名不能为空",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "104": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ListResponse"
                        }
                    }
                }
            }
        },
        "/api/db/page": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库通用操作"
                ],
                "summary": "分页查询数据",
                "responses": {
                    "101": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "102": {
                        "description": "表名不能为空",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "103": {
                        "description": "获取总数失败",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "104": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "查询结果",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.PageResponse"
                        }
                    }
                }
            }
        },
        "/api/db/save": {
            "post": {
                "description": "通用数据保存接口，支持新增和更新操作，自动根据是否有id字段判断操作类型",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据库通用操作"
                ],
                "summary": "保存数据",
                "responses": {
                    "101": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "102": {
                        "description": "表名不能为空",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "103": {
                        "description": "保存数据不能为空",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "104": {
                        "description": "缺少必填字段",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "105": {
                        "description": "必填字段不能为空",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "106": {
                        "description": "没有需要更新的数据",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "107": {
                        "description": "更新失败",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "108": {
                        "description": "获取更新后数据失败",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "109": {
                        "description": "插入失败",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.ErrorResponse"
                        }
                    },
                    "200": {
                        "description": "保存成功，返回保存后的数据",
                        "schema": {
                            "$ref": "#/definitions/dbcommon.SaveResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dbcommon.DeleteResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "type": "string",
                    "example": "删除成功"
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "dbcommon.DetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "记录详情",
                    "type": "object",
                    "additionalProperties": true
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "dbcommon.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码",
                    "type": "integer",
                    "example": 101
                },
                "data": {
                    "description": "错误数据",
                    "type": "string",
                    "example": "null"
                },
                "msg": {
                    "description": "错误消息",
                    "type": "string",
                    "example": "错误信息"
                }
            }
        },
        "dbcommon.ListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "dbcommon.PageData": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "has_next": {
                    "description": "是否有下一页",
                    "type": "boolean"
                },
                "has_prev": {
                    "description": "是否有上一页",
                    "type": "boolean"
                },
                "page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                },
                "total_pages": {
                    "description": "总页数",
                    "type": "integer"
                }
            }
        },
        "dbcommon.PageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "分页数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dbcommon.PageData"
                        }
                    ]
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "dbcommon.SaveResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "保存后的数据",
                    "type": "object",
                    "additionalProperties": true
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "sysbase.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码",
                    "type": "integer",
                    "example": 101
                },
                "data": {
                    "description": "错误数据",
                    "type": "string",
                    "example": "null"
                },
                "msg": {
                    "description": "错误消息",
                    "type": "string",
                    "example": "错误信息"
                }
            }
        },
        "sysbase.LoginRequest": {
            "type": "object",
            "required": [
                "code",
                "password"
            ],
            "properties": {
                "code": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                },
                "password": {
                    "description": "密码(SM2加密)",
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "sysbase.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "返回的token",
                    "type": "string",
                    "example": "token-uuid"
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "sysbase.LoginUserDetail": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "integer",
                    "example": 1
                },
                "memo": {
                    "description": "权限备注",
                    "type": "string",
                    "example": "权限备注"
                },
                "role_id": {
                    "description": "角色ID",
                    "type": "integer",
                    "example": 1
                },
                "role_name": {
                    "description": "角色名称",
                    "type": "string",
                    "example": "管理员"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "sysbase.LogoutResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "响应数据",
                    "type": "string",
                    "example": "退出成功"
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "sysbase.MenuResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "菜单树形结构",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        },
        "sysbase.UserInfoResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "用户详细信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/sysbase.LoginUserDetail"
                        }
                    ]
                },
                "msg": {
                    "description": "响应消息",
                    "type": "string",
                    "example": "操作成功"
                }
            }
        }
    },
    "securityDefinitions": {
        "TokenAuth": {
            "description": "Token认证",
            "type": "apiKey",
            "name": "Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "FirstWeb API接口文档",
	Description:      "FirstWeb项目API接口说明，支持用户认证和数据库通用操作",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
